language: csharp
solution: ./AssignmentDemo/AssignmentDemo.sln

before_install:
  - sudo apt-get install nunit-console
install:
  - nuget restore ./AssignmentDemo/AssignmentDemo.sln
script:
  - xbuild ./AssignmentDemo/AssignmentDemo.sln
  - nunit-console ./AssignmentDemo/AssignmentDemo/bin/Debug/AssignmentDemoTests.dll
